980 ams election samlow
ubyssey/ubyssey-dispatch-theme pull request #1084
Opened 2023-05-09 21:34 UTC by SamuelmdLow

## What problem does this PR solve?

fixed issue #980 

## How did you fix the problem?

Created a page links block and a header block. Clicking a page link will send the user to the header which shares the id

2023-06-05 07:18 UTC, FireBoyAJ24 requested changes
Can we add all the inline styles and the scripts to be in external style sheets and scripts?

2023-06-20 06:18 UTC, FireBoyAJ24 approved these changes
The !important is a small aspect and will hopefully not impact the rest of the code base but it is best avoided unless all options have been dried up.

2023-06-20 06:18 UTC, FireBoyAJ24 commented on article/templates/article/stream_blocks/pageLink.html
> +                         background-color: #{{item.colour}} !important;
Is there anyway to avoid !important?

2023-06-22 11:35 UTC, SamuelmdLow commented on article/templates/article/stream_blocks/pageLink.html
> +                         background-color: #{{item.colour}} !important;
I've removed it. Turns out it wasn't actually important

2023-08-04 17:36 UTC, SamuelmdLow commented
Merged into redesign

2023-08-04 17:36 UTC, closed without merging