1097 we should add share options to all the articles
ubyssey/ubyssey-dispatch-theme pull request #1100
Opened 2023-05-30 10:16 UTC by FireBoyAJ24

Instead of a sidebar. I have chosen to add a discreet horizontal share bar for the main article page, wide page and 2023 magazine page. However, I could not test the guide pages as well as the old magazines pages (prior 2023).

Main article page:
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/ea387997-0f0f-4538-a165-5b5a8fbf8ba6)

Wide article page:
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/032b44d0-a08a-46cb-b6d2-8235c8bade01)

Magazine 2023 page:
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/f03020b2-1b1d-4180-97a1-c731e9c01a9c)

2023-06-05 23:44 UTC, SamuelmdLow requested changes
Javascript did not work when I tested it. 

The address to share to facebook is missing the argument name "u". It should be  `http://facebook.com/sharer.php?u=' + window.location.href`. 

Also the variable `titleElement` is a list of elements with the tag "title". The innerText of a list returns undefined. titleElement should instead be the first element of this list: `const titleElement = document.getElementsByTagName("title")[0];`

I'm also unsure if these three social medias are actually the best to include. There is a design cost that comes with including unused features. I don't think a lot of university students are posting on linkedin. Even facebook and twitter aren't that widely used for our age group. I think reddit might be more useful to the website - especially because UBC has a pretty active subreddit. It might be useful to ask the editors about this

2023-06-06 06:11 UTC, FireBoyAJ24 commented
> Javascript did not work when I tested it.
> 
> The address to share to facebook is missing the argument name "u". It should be `http://facebook.com/sharer.php?u=' + window.location.href`.
> 
> Also the variable `titleElement` is a list of elements with the tag "title". The innerText of a list returns undefined. titleElement should instead be the first element of this list: `const titleElement = document.getElementsByTagName("title")[0];`
> 
> I'm also unsure if these three social medias are actually the best to include. There is a design cost that comes with including unused features. I don't think a lot of university students are posting on linkedin. Even facebook and twitter aren't that widely used for our age group. I think reddit might be more useful to the website - especially because UBC has a pretty active subreddit. It might be useful to ask the editors about this

When I began work on the share button feature, I stumbled on a piece of code which allowed us to share articles to different social media apps. The one that was chosen by the previous developer included reddit.

2023-06-07 01:05 UTC, SamuelmdLow approved these changes

2023-07-06 10:39 UTC, brittkhat commented
I got some weird interactions when I checked the branch in my local dev environment. It produced a text box and the links don't seem to work in my setup. 
![image](https://github.com/ubyssey/ubyssey.ca/assets/83617860/118eb47d-0445-4ae7-9509-bd8abf1e40e4)

2023-07-06 10:43 UTC, FireBoyAJ24 commented
> I got some weird interactions when I checked the branch in my local dev environment. It produced a text box and the links don't seem to work in my setup. ![image](https://user-images.githubusercontent.com/83617860/251426093-118eb47d-0445-4ae7-9509-bd8abf1e40e4.png)

Have you done gulp build?

2023-07-13 04:11 UTC, merged