Created audio quote block
ubyssey/ubyssey-dispatch-theme pull request #1109
Opened 2023-06-07 10:10 UTC by SamuelmdLow

Copied the quote block but had it play audio when clicked

2023-06-20 05:33 UTC, FireBoyAJ24 requested changes
I looked up online and found that audio was not fully supported by wagtail. Do you want to try out the [wagtailmedia](https://github.com/torchbox/wagtailmedia) so that it can allow us to reduce the complexity in the backend?

2023-06-20 05:33 UTC, FireBoyAJ24 commented on article/models.py
> +                    ('source',blocks.CharBlock(required=False)),
Can you add a help text to explain what the content and source does?

2023-06-20 05:33 UTC, FireBoyAJ24 commented on article/templates/article/article_page_magazine_2023.html
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/1dac4441-e042-4edf-82f2-6898e193bebd)

The quote is not aligned correctly.

2023-06-21 13:34 UTC, SamuelmdLow commented on article/templates/article/article_page_magazine_2023.html
I feel like you didn't run `gulp build`

2023-06-23 12:36 UTC, FireBoyAJ24 approved these changes

2023-07-06 16:39 UTC, SamuelmdLow commented
Going to put in visual essay

2023-07-06 16:39 UTC, closed without merging