Redesign!!!
ubyssey/ubyssey-dispatch-theme pull request #1124
Opened 2023-06-27 15:35 UTC by SamuelmdLow

![image](https://github.com/ubyssey/ubyssey.ca/assets/67992154/f57909ae-12a8-4627-8761-535fac6c027d)

![image](https://github.com/ubyssey/ubyssey.ca/assets/67992154/f69104aa-262c-43df-b248-013d065714e0)

![image](https://github.com/ubyssey/ubyssey.ca/assets/67992154/cac37750-c1f5-46b1-a2aa-c6e54c167dfb)

2023-07-06 12:16 UTC, FireBoyAJ24 requested changes, later dismissed
1. There is a small bug where I see show more when the homepage page states that I have reached the end. In addition, when I search using the search bar in the section page, if there is no results it says, You reached the end.

2. The loading sign is oddly placed in the mobile screen.

3. The debug system sends a complaint with the function, get_paginated_articles()
to replicate the error, http://localhost:8000/archive/?q=Type-anything-here.

4. If the author's bio is long, the container cuts into the nav bar.

5. Do you want to keep the formatting the same for the section page and the archive page? For example, the archive page will have an infinite feed or the section page will not have an infinite feed.

2023-07-06 12:16 UTC, FireBoyAJ24 commented on archive/models.py
> +    """
These comments are not needed.

2023-07-06 12:16 UTC, FireBoyAJ24 commented on archive/templates/archive/archive_page.html
>              <h1 class="c-page__heading">Search the archive</h1>
Just need to capitalize the archive name. Do we need to have the heading very large.

2023-07-06 12:16 UTC, FireBoyAJ24 commented on archive/templatetags/archive_tags.py
> +    return parameters
Could we have used {{ request.GET }} instead of making a separate tag.

2023-07-06 12:16 UTC, FireBoyAJ24 commented on article/templates/article/objects/blog_column.html
> +<article class="o-article o-article--column{% if padded %} o-article--padded{% endif %}" style="background-color: {{article|get_colour}}">
Is there meant to be a CSS style in the article tag? Can the style be placed in a class, or is it too much?

2023-07-06 16:36 UTC, SamuelmdLow commented
To do: Add dark mode

2023-08-04 10:33 UTC, FireBoyAJ24 approved these changes
Asa beta I accept the redesign. We may still want to discuss about the suggested articles style as the sidebar suggested articles may feel a bit jarring.

2023-08-09 22:04 UTC, merged

2023-08-09 22:53 UTC, brittkhat commented
lgtm