Switch to ES6
ubyssey/ubyssey-dispatch-theme pull request #180
Opened 2017-01-27 08:52 UTC by blx

- enables the `es2015` babel preset (everything was being babelified for jsx already anyway)
- adds jasmine (`gulp jasmine`) and a whopping four test cases
- should and seems to behave 100% the same way (no api changes)

🐲

2017-02-02 06:38 UTC, psiemens requested changes

2017-02-02 06:38 UTC, psiemens commented on ubyssey/static/src/js/components/Search.jsx
> +                <ul className={"results" + (this.state.results.length > 0 && " open")}>{results}</ul>
`(this.state.results.length > 0 && " open")`

This appends "false" to the className when `results.length == 0`.

2017-02-02 06:38 UTC, psiemens commented on ubyssey/static/src/js/components/Search.jsx
> +                    <input ref="search" className={this.state.results.length > 0 && "open"} name="q" id="search-bar" type="text" autoComplete="off" onChange={this.updateQuery} value={this.state.q} pl
Same as below 👇

2017-02-02 06:38 UTC, psiemens commented on ubyssey/static/gulpfile.js
> +require('babel-register'); // Pass require()s through babel (for running jasmine)
`babel-register` is missing in `package.json`

2017-02-02 08:13 UTC, blx commented on ubyssey/static/src/js/components/Search.jsx
> +                <ul className={"results" + (this.state.results.length > 0 && " open")}>{results}</ul>
yeah my bad, this works for conditionally rendering JSX but not strings

2017-02-02 08:15 UTC, blx commented on ubyssey/static/gulpfile.js
> +require('babel-register'); // Pass require()s through babel (for running jasmine)
good catch, updated.

2017-02-10 04:46 UTC, psiemens approved these changes

2017-02-10 04:47 UTC, psiemens commented
Everything *seems* to be working (I'm pretty sure I tested every component on the site).

Merging into staging for now -- will test again before next release.

2017-02-10 04:47 UTC, merged

2017-02-10 04:59 UTC, blx commented
Cool! I tried to test things as I went too, and the translations were largely mechanical, so there shouldn't be too many dragons lurking. 🤔