89 change article font size
ubyssey/ubyssey-dispatch-theme pull request #201
Opened 2017-02-08 00:55 UTC by sjason19

I was wondering what the conversion from px to em was, not too sure where to find out the base em?
thanks

2017-02-08 05:12 UTC, psiemens commented
@sjason19 haha no worries

2017-02-10 22:29 UTC, psiemens requested changes

2017-02-10 22:29 UTC, psiemens commented on ubyssey/static/src/styles/modules/article/_base.scss
>      font-size: 17px !important;
We have a SASS helper function that automatically converts `px` to `em`. You can use it like this:

 ```sass
font-size: font-size(17) !important;
```

2017-02-10 22:29 UTC, psiemens commented on ubyssey/static/src/styles/modules/article/_base.scss
> +    line-height: 27px !important;
Change this to use `em` like this:

```sass
line-height: 1.55em !important;
```

2017-02-10 22:29 UTC, psiemens commented on ubyssey/static/src/styles/modules/article/_base.scss
> +    margin-top: 27px;
Let's use `1.4em` here instead of pixels:

```sass
margin-top: 1.4em;
```

2017-02-12 00:06 UTC, b1s0ndev reviewed
didnt mean to do this sorry

2017-02-12 00:07 UTC, b1s0ndev reviewed
let me know if this is all that had to be changed :)

2017-02-12 06:14 UTC, psiemens commented
Perfect, thanks @sjason19!

2017-02-12 06:14 UTC, psiemens approved these changes

2017-02-12 06:14 UTC, merged