Small change to public event form css
ubyssey/ubyssey-dispatch-theme pull request #271
Opened 2017-07-07 20:48 UTC by Axel-Jacobsen

:

2017-07-07 22:56 UTC, joncppl commented
can you PR into the develop branch instead?

2017-07-13 05:51 UTC, psiemens commented
Updates I made:

- Moved template files from `dispatch` to `ubyssey-dispatch-theme`
- Used the `.c-header` component class for the title and description
- Form is no longer centered -- I decided it looks better left-aligned
- Moved your three scss files into `components/events/submit` and linked to them from the `main.scss` (instead of loading one in each template)
- Created a new class `.c-event-submit-landing`
- When a Facebook error is encountered, it is displayed at the top of the form page. Right now I'm just displaying text, but here's an updated Zeplin board for how it should look: https://zpl.io/Z2tJ6NL

2017-07-13 17:45 UTC, psiemens requested changes

2017-07-13 17:45 UTC, psiemens commented on ubyssey/static/src/styles/components/events/_event-submit-form.scss
> +.c-form-input {
All of the `.c-form-input` classes should be in their own file: `components/_form-input.scss`

2017-07-13 17:45 UTC, psiemens commented on ubyssey/static/src/styles/components/events/_event-submit-form.scss
> +input[type=text], input[type=email], input[type=tel], textarea {
Use classes instead of element targets:

```scss
.c-input--text,
.c-input--email,
.c-input--tel {
  // ...
}

2017-07-13 17:45 UTC, psiemens commented on ubyssey/static/src/styles/components/events/_event-submit-form.scss
> +  border: 2px solid rgba(0,0,0,0.075);
The styles for the text input seem a little off. Try copying them from this page: https://ubyssey.github.io/styles/inputs

2017-07-20 14:21 UTC, psiemens approved these changes

2017-07-20 18:21 UTC, merged