Upcoming events widget
ubyssey/ubyssey-dispatch-theme pull request #279
Opened 2017-07-14 04:27 UTC by joncppl

This is dependent on the event box I implemented in event-calendar, so I'm selecting it as base.

But the upcoming event widgets is done!
Has a featured event that will display with the image, and a configurable list of upcoming events that won't display the image. 

I added two zones on the homepage.

Possible improvements (these were Ron's ideas from a while ago):
- carousel the featured image (doable with javascript)
- make the event list scroll (easy with css)

2017-07-17 16:43 UTC, psiemens requested changes
🙌 Code looks great! Haven't had a chance to preview the design, but I'll submit another review once I do

2017-07-17 16:43 UTC, psiemens commented on ubyssey/widgets.py
> +  def prepare_data(self):
Now that the fix in https://github.com/ubyssey/dispatch/pull/621 is merged, you should be able to override `context` instead of `prepare_data`.

2017-07-17 16:43 UTC, psiemens commented on ubyssey/static/src/styles/modules/widgets/upcoming_events.scss
> +  margin-bottom: 10px;
Use `em`

2017-07-17 16:43 UTC, psiemens commented on ubyssey/static/src/styles/modules/widgets/upcoming_events.scss
> +    margin-bottom: 5px;
Use `em`

2017-07-17 16:43 UTC, psiemens commented on ubyssey/static/src/styles/modules/widgets/upcoming_events.scss
> +  margin-bottom: 3px;
Use `em`

2017-07-17 16:43 UTC, psiemens commented on ubyssey/static/src/styles/modules/widgets/upcoming_events.scss
> +  font-weight: 600;
`font-weight: $font-weight-semi-bold`

2017-07-17 16:43 UTC, psiemens commented on ubyssey/static/src/styles/modules/widgets/upcoming_events.scss
> +  font-size: 0.8em;
You can use the `font-size` function to convert px to em:
```scss
font-size: font-size(13);
```

2017-07-17 16:43 UTC, psiemens commented on ubyssey/widgets.py
> +    result = super(UpcomingEvents, self).prepare_data()
When you override `context`, you won't have to call `super`

2017-07-17 16:43 UTC, psiemens commented on ubyssey/widgets.py
> +        N = int(result['number_of_events'], base=10)
I'd prefer to use a more descriptive variable, something like `num_events`

2017-07-17 18:40 UTC, joncppl commented
note: it now depends on https://github.com/ubyssey/dispatch/pull/624/files

2017-07-24 03:22 UTC, psiemens approved these changes

2017-07-24 16:14 UTC, psiemens commented
Made a few small style tweaks -- merging now!

2017-07-24 16:14 UTC, merged