implement carousel
ubyssey/ubyssey-dispatch-theme pull request #296
Opened 2017-07-27 19:27 UTC by joncppl

- tweak the widget to take multiple featured events
- the django template applies style="display: none;" to all but the first (so that multiple aren't visible if the JS/CSS has't loaded yet)

- simple jQuery adds automatic slide change every 5 second.
- also adds buttons that stop the slideshow and allow manual movement through slides.
- registers all widgets separately, so multiple upcoming-event-widgets can be on the same page and work independently.

2017-07-28 03:12 UTC, psiemens requested changes

2017-07-28 03:12 UTC, psiemens commented on ubyssey/static/src/styles/modules/widgets/_upcoming_events.scss
> +.carousel {
Use `.c-upcoming-events__` prefix

2017-07-28 03:12 UTC, psiemens commented on ubyssey/static/src/js/widgets/upcoming-events.js
> +  $('.carousel').each(function() {
Use a `.js-carousel` class for JavaScript targeting

2017-07-28 03:12 UTC, psiemens commented on ubyssey/static/src/js/widgets/upcoming-events.js
> +    carousel.find('.carousel-item').each(function(i) {
`.js-carousel__item`

2017-07-28 03:12 UTC, psiemens commented on ubyssey/static/src/js/widgets/upcoming-events.js
> +      }, 5000);
Make `5000` a constant

2017-07-28 03:14 UTC, psiemens commented
Good thinking with the JavaScript fallback -- nicely implemented. 

I'm not sure I love the arrows. What about something like this? Clicking a dot would take you to that "slide":

![screen shot 2017-07-27 at 11 04 35 pm](https://user-images.githubusercontent.com/2547035/28701005-44f3effa-7321-11e7-87f8-8159ada859f2.png)

Also, would it be possible to animate between slides?

2017-07-28 21:26 UTC, joncppl commented
I went with a lightweight manual approach here.

But it might be worthwhile to use a library for animation and other features.
What do you think about http://kenwheeler.github.io/slick/ ?

Would probably work well for the horizontal event widget as well.

2017-07-28 22:25 UTC, joncppl commented
Actually that library doesn't work well with our existing css. 
It exploded and made the div ~ 1M x 1M px big. 

So I did the carousel indicators and animation manually. not that much more complicated.

2017-07-31 17:50 UTC, psiemens requested changes
Can you post a screenshot of the updated design? I can't build the project right now.

2017-07-31 17:50 UTC, psiemens commented on ubyssey/templates/widgets/upcoming-events.html
> +    <div class="c-widget-upcoming-events__featured js-carousel__item" {% ifnotequal forloop.counter0 0 %}style="display:none;"{% endifnotequal %}>
You can use css selectors for this:

```scss
.c-widget-upcoming-events__featured {
  display: none;
  
  &:first-child {
    display: block;
  }
}

2017-07-31 17:50 UTC, psiemens commented on ubyssey/static/src/js/widgets/upcoming-events.js
> +          if (slide.css('display') != 'none') {
```js
if (slide.is(':visible')) {
  ...
}

2017-07-31 20:44 UTC, joncppl commented
![image](https://user-images.githubusercontent.com/624196/28797476-4f1e77ca-75f6-11e7-9583-64fc6e8b9463.png)

animates with a quick fadein->fadeout

2017-08-01 15:17 UTC, psiemens approved these changes

2017-08-01 18:37 UTC, merged