Frontpage zone + live streaming!
ubyssey/ubyssey-dispatch-theme pull request #303
Opened 2017-08-16 18:51 UTC by joncppl

implements a zone that controls the front page of the website

2 widgets:

1. default layout as it is now; with nested widget to control sidebar
2. facebook video/live streaming widget!

2017-08-16 21:18 UTC, joncppl commented
not really sure where to store it, but here is the live streaming doc I've been working on
https://drive.google.com/open?id=0BzsUSSbiJooHaHdNT0xndlpsWUE

2017-08-21 19:01 UTC, psiemens requested changes

2017-08-21 19:01 UTC, psiemens commented on ubyssey/widgets.py
> +
Remove empty line

2017-08-21 19:01 UTC, psiemens commented on ubyssey/widgets.py
> +    host = CharField('Video Hoster (will display as author)')
Change `Video Hoster` to `Video Host`

2017-08-21 19:01 UTC, psiemens commented on ubyssey/templates/widgets/frontpage/facebook-video-big.html
> +}(document, 'script', 'facebook-jssdk'));</script>
The Facebook SDK is already loaded in `templates/base.html`. Does it have to be reloaded?

2017-08-21 19:01 UTC, psiemens commented on ubyssey/static/src/styles/modules/widgets/_facebook_video_big.scss
> +  box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.05);
Fix indentation

2017-08-21 19:01 UTC, psiemens commented on ubyssey/templates/widgets/frontpage/facebook-video-big.html
> +				<div class="fb-comments" data-href="{{ video_url }}" data-width="350" data-numposts="5"></div>
Maybe reduce `numposts` to 3 and set overflow to `scroll` to prevent this element from growing too tall

2017-08-22 18:27 UTC, psiemens approved these changes

2017-08-22 19:25 UTC, merged