Ubc event cron
ubyssey/ubyssey-dispatch-theme pull request #353
Opened 2017-09-28 00:30 UTC by Axel-Jacobsen

Here is the Cron job, albeit a little late. I believe that it should work, but it is a little difficult to test.

2017-09-29 18:01 UTC, psiemens requested changes
Looks good! Added some suggestions.

Do you think it would make sense to remove the manage command now that it has its own URL? I just find it a little confusing having the `main` method inside `import_events.py`

2017-09-29 18:01 UTC, psiemens commented on ubyssey/events/management/commands/import_events.py
> +    http_status = feedObj.feed.status
I'd prefer to have a cleaner interface for the `UBCEventsRSSFeed`. Something along these lines:

```py
feed = UBCEventsRSSFeed('http://services.calendar.events.ubc.ca/cgi-bin/rssCache.pl?days=2&mode=rss')

updated = feed.update()

if updated:
  status = SOME_VALUE
else:
  status = SOME_OTHER_VALUE

2017-09-29 18:01 UTC, psiemens commented on ubyssey/events/management/commands/import_events.py
> +    return HttpResponse(status=http_status)
Would it be possible for this response to also include a short summary of the results? Maybe a JSON payload:

```json
{
  "added": 12,
  "removed": 3
}

2017-09-29 18:01 UTC, psiemens commented on ubyssey/events/urls.py
> +    url(r'^import/', views.event_import, name='events-import'),
`views.event_import` can just be `views.import`

2017-10-11 16:38 UTC, Axel-Jacobsen commented on ubyssey/events/urls.py
> +    url(r'^import/', views.event_import, name='events-import'),
wouldn't having a method called `import` conflict with the `import` keyword in python?

2017-10-11 16:52 UTC, Axel-Jacobsen commented on ubyssey/events/management/commands/import_events.py
> +    http_status = feedObj.feed.status
I dont think i quite understand the purpose of this; I made some changes and pushed so take a look?  I think I completed the goal of this code snippet

2017-10-22 21:46 UTC, psiemens approved these changes

2017-10-22 21:46 UTC, merged