created Twitter widget
ubyssey/ubyssey-dispatch-theme pull request #406
Opened 2018-01-10 21:49 UTC by rithikha

Created (twitter widget) #340

2018-01-24 19:54 UTC, jumbosushi reviewed
Great start! There's a django bug when I run the site with this which I'll look into, but let's try to fix these styles first

2018-01-24 19:54 UTC, jumbosushi commented on ubyssey/static/src/styles/modules/widgets/_facebook_video_big.scss
> +  font-weight: 800;
Missing spacing here

2018-01-24 19:54 UTC, jumbosushi commented on ubyssey/widgets.py
> +<<<<<<< Updated upstream
Still have git merge leftovers in this file haha

2018-01-24 19:54 UTC, jumbosushi commented on ubyssey/static/src/styles/modules/widgets/_twitter.scss
> +height: 30rem;
Need spacing here

2018-01-24 19:54 UTC, jumbosushi commented on ubyssey/static/src/styles/modules/widgets/_facebook_video_big.scss
> +	.c-facebook-video__title {
Spacing is bit different from others in here

2018-01-25 18:24 UTC, psiemens commented on ubyssey/widgets.py
> +<<<<<<< Updated upstream
This could be what's causing the server to crash

2018-02-14 20:16 UTC, psiemens requested changes

2018-02-14 20:16 UTC, psiemens commented on ubyssey/templates/widgets/frontpage/twitter-front-page.html
> +<a class="twitter-timeline" href="https://twitter.com/ubyssey"></a>
This shouldn't be hardcoded -- you can return the `{{ handle }}` value that is saved by the widget.

2018-02-14 21:38 UTC, merged