433 article poll embed
ubyssey/ubyssey-dispatch-theme pull request #455
Opened 2018-06-01 23:08 UTC by Rowansdabomb

2018-06-06 20:16 UTC, psiemens requested changes

2018-06-06 20:16 UTC, psiemens commented on package.json
> +{
These should go in `ubyssey.ca/ubyssey/static/package.json`

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/package.json
> +    "Rowan Baker-French"
Add Jamie too!

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/api/dispatch.js
> +    getResults: (id) => {
I would just name this route `get` since it returns the entire poll detail

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/article.jsx
> +
Remove extra line

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/article.jsx
> +$(document).ready(function() {
You can use the JQuery shorthand if you want to clean this up a bit:

```js
$(function() {

})

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/article.jsx
> +            <Poll many={false} id={$(this).data('id')} />,
Should the `many` prop be set dynamically?

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Article.jsx
> +
Remove the extra empty lines in this file

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +        {pole_id: this.props.id, vote_id: vote_id, answer_id: answer_id},
Typo: "pole"

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +    let answer_id = Number(this.getCookie('answer_id'))
These can both be `const`

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +      for(let answer of response.answers){
Space after `for`

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +      if(init){
Space after `if`

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +        let cookie = this.getCookie()
`const`

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +        if(!cookie || !cookie.answer_id){
Space after `if`

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +      let answer_ids = []
Use camelcase: `answerIds`

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +      let vote_id = this.getCookie('vote_id')
Camelcase

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +      let totalVotes = response.total_votes
Don't need to define this variable

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +          this.setState({
Why is this happening in a separate `setState` call?

2018-06-06 20:16 UTC, psiemens commented on ubyssey/templates/embeds/poll.html
> +<div class="poll-attachment">
Delete this file

2018-06-06 20:16 UTC, psiemens commented on ubyssey/templates/widgets/poll.html
> +  Loading Poll...
I would change to "Loading poll..."

2018-06-06 20:16 UTC, psiemens commented on ubyssey/widgets.py
> +  name = 'Poll Widget'
I would just call the widget `poll` and `Poll`

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +          this.setState({
I think you can combine them into one -- or am I wrong?

2018-06-06 20:16 UTC, psiemens commented on ubyssey/static/src/js/components/Poll.jsx
> +        let payload = {poll_id: this.props.id, vote_id: this.state.vote_id, answer_id: this.state.answer_ids[this.state.checkedAnswers[0]]}
For readability:

```js
const payload = {
  poll_id: this.props.id, 
  vote_id: this.state.vote_id, 
  answer_id: this.state.answer_ids[this.state.checkedAnswers[0]]
}

2018-06-07 01:09 UTC, Rowansdabomb commented on ubyssey/static/src/js/article.jsx
> +$(document).ready(function() {
cool, didn't know about that

2018-06-07 01:10 UTC, Rowansdabomb commented on ubyssey/static/src/js/article.jsx
> +            <Poll many={false} id={$(this).data('id')} />,
I am removing the many feature all together for the initial release as it is incomplete. If we want to add the ability for polls to accept multiple answers we can do so later

2018-06-07 01:20 UTC, Rowansdabomb commented on ubyssey/static/src/js/components/Poll.jsx
> +          this.setState({
i use this.state.answer_ids, so i wait for it to be set, but you are correct, i can refactor using the temp variable answer_ids

2018-06-11 22:11 UTC, merged