480 remove article continuous scroll
ubyssey/ubyssey-dispatch-theme pull request #482
Opened 2018-06-19 22:59 UTC by Rowansdabomb

2018-06-19 23:00 UTC, Rowansdabomb commented
PR for issues 466, 472, 480

2018-06-21 19:24 UTC, JamieRL approved these changes
Reviewed together with @Rowansdabomb

2018-06-25 19:01 UTC, psiemens requested changes
I'm wondering if it makes more sense to insert the suggested articles as plain HTML rather than React. Since the mobile layout will be using a separate carousel, I'm not sure it's necessary to use React in the desktop view. Thoughts? @JamieRL @Rowansdabomb

2018-06-25 19:01 UTC, psiemens commented on ubyssey/helpers.py
> +    def insert_ads(article, article_type = 'desktop'):
Remove extra spaces:

```py
def insert_ads(article, article_type='desktop'):
```

2018-06-25 19:01 UTC, psiemens commented on ubyssey/helpers.py
> +        """ inject upto 5 ads evenly throughout the article content
Capitalize and punctuate:

```py
"""Inject up to 5 ads evenly throughout the article content. 
Ads can not inject directly beneath headers.""

2018-06-25 19:01 UTC, psiemens commented on ubyssey/helpers.py
> +                paragraph_count += 1
Here's a one-liner if you want to reduce code:

```py
paragraph_count = len(filter(lambda b: b['type'] == 'paragraph', article.content))

2018-06-25 19:01 UTC, psiemens commented on ubyssey/helpers.py
> +        numberOfAds = 1
Use underscores instead of camelcase

2018-06-25 19:01 UTC, psiemens commented on ubyssey/helpers.py
> +            if tag in explicit_tags:
You can do this:

```py
explicit_tags = ['sex', 'explicit']
# ...
if tag.lower() in explicit_tags:

2018-06-25 19:01 UTC, psiemens commented on ubyssey/helpers.py
> +            unicode('data'): unicode(article_type)
Why the unicode wrapping?

2018-06-25 19:01 UTC, psiemens commented on ubyssey/static/src/js/components/ArticlePreview.jsx
> +  }
You can take this method out

2018-06-25 19:01 UTC, psiemens commented on ubyssey/static/src/js/components/ArticlePreview.jsx
> +  }
Is this method still needed?

2018-06-25 19:01 UTC, psiemens commented on ubyssey/views/main.py
> +            article = ArticleHelper.insert_ads(article, article_type)
I'd prefer if this was called like this:

```py
article.content = ArticleHelper.insert_ads(article.content, article_type)

2018-06-25 19:01 UTC, psiemens commented on ubyssey/views/main.py
>      def article_ajax(self, request, pk=None):
Do we even need this route anymore?

2018-06-25 19:03 UTC, JamieRL commented on ubyssey/helpers.py
> +            if tag in explicit_tags:
nice

2018-06-29 21:48 UTC, merged