remove mobile spacer from frontpage on desktop
ubyssey/ubyssey-dispatch-theme pull request #536
Opened 2018-08-22 18:50 UTC by Rowansdabomb

2018-08-22 18:52 UTC, JamieRL requested changes
just 1 thing. Looks good

2018-08-22 18:52 UTC, JamieRL commented on ubyssey/templates/homepage/base.html
> +{% if is_mobile%}
add space before last `%`

2018-08-22 18:55 UTC, Rowansdabomb commented on ubyssey/templates/homepage/base.html
> +{% if is_mobile%}
nice catch

2018-08-22 18:56 UTC, Rowansdabomb commented
fixed the spacing, should be ready to merge

2018-08-28 18:49 UTC, JamieRL approved these changes

2018-08-29 16:59 UTC, merged