Add message in case no events are in the selected week
ubyssey/ubyssey-dispatch-theme pull request #654
Opened 2019-05-01 10:05 UTC by d1vyanshu

## What problem does this PR solve?
Earlier there was no response if no events were there in selected week. Now a message is dispalyed.

#647 

## How did you fix the problem?
By adding (% empty %} tag in code so that message can be displayed.

Just added {% empty %} tag and the message

2019-05-05 21:13 UTC, jumbosushi requested changes
Thanks for the PR!  Looks great :100:  Just need to fix the grammer and we can merge it
Sorry about the CI error. We're looking into the ways for us to enable Travis from forked repos.

2019-05-05 21:13 UTC, jumbosushi commented on ubyssey/templates/events/events.html
> +        There is no events scheduled for this week.
Think changing `is` to `are` sounds more natural

2019-05-05 21:17 UTC, jumbosushi commented
Also we love getting a pr from across the world ☺️ Just curious where did you find out about our repo?

2019-05-06 07:16 UTC, d1vyanshu commented
I have corrected the grammar. I have keen interest in learning programming and just started exploring the open source world by starting off by searching beginners issue and found this. Thanks for giving the chance !

2019-05-06 18:09 UTC, merged

2019-05-06 18:09 UTC, jumbosushi commented
Great work :clap: